src/Entity/Conducteur.php
<?php

namespace App\Entity;

use App\Repository\ConducteurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConducteurRepository::class)
 */
class Conducteur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\Column(type="integer")
     */
    private $tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero_vol;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

//    /**
//     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="conducteur")
//     */
//    private $id_reserveation;

    /**
     * @ORM\ManyToOne(targetEntity=Reservation::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $reservation_id;

//    public function __construct()
//    {
//        $this->id_reserveation = new ArrayCollection();
//    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getTel(): ?int
    {
        return $this->tel;
    }

    public function setTel(int $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    public function getNumeroVol(): ?string
    {
        return $this->numero_vol;
    }

    public function setNumeroVol(?string $numero_vol): self
    {
        $this->numero_vol = $numero_vol;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getIdReserveation(): Collection
    {
        return $this->id_reserveation;
    }

//    public function addIdReserveation(Reservation $idReserveation): self
//    {
//        if (!$this->id_reserveation->contains($idReserveation)) {
//            $this->id_reserveation[] = $idReserveation;
//            $idReserveation->setConducteur($this);
//        }
//
//        return $this;
//    }
//
//    public function removeIdReserveation(Reservation $idReserveation): self
//    {
//        if ($this->id_reserveation->removeElement($idReserveation)) {
//            // set the owning side to null (unless already changed)
//            if ($idReserveation->getConducteur() === $this) {
//                $idReserveation->setConducteur(null);
//            }
//        }
//
//        return $this;
//    }

    public function getReservationId(): ?Reservation
    {
        return $this->reservation_id;
    }

    public function setReservationId(?Reservation $reservation_id): self
    {
        $this->reservation_id = $reservation_id;

        return $this;
    }
}

src/Controller/AdminConducteurController.php
<?php

namespace App\Controller;

use App\Entity\Conducteur;
use App\Form\Conducteur1Type;
use App\Repository\ConducteurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/conducteur")
 */
class AdminConducteurController extends AbstractController
{
    /**
     * @Route("/", name="app_admin_conducteur_index", methods={"GET"})
     */
    public function index(ConducteurRepository $conducteurRepository): Response
    {
        return $this->render('admin_conducteur/index.html.twig', [
            'conducteurs' => $conducteurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_admin_conducteur_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ConducteurRepository $conducteurRepository): Response
    {
        $conducteur = new Conducteur();
        $form = $this->createForm(Conducteur1Type::class, $conducteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $conducteurRepository->add($conducteur, true);

            return $this->redirectToRoute('app_admin_conducteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_conducteur/new.html.twig', [
            'conducteur' => $conducteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_conducteur_show", methods={"GET"})
     */
    public function show(Conducteur $conducteur): Response
    {
        return $this->render('admin_conducteur/show.html.twig', [
            'conducteur' => $conducteur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_admin_conducteur_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Conducteur $conducteur, ConducteurRepository $conducteurRepository): Response
    {
        $form = $this->createForm(Conducteur1Type::class, $conducteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $conducteurRepository->add($conducteur, true);

            return $this->redirectToRoute('app_admin_conducteur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_conducteur/edit.html.twig', [
            'conducteur' => $conducteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_conducteur_delete", methods={"POST"})
     */
    public function delete(Request $request, Conducteur $conducteur, ConducteurRepository $conducteurRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$conducteur->getId(), $request->request->get('_token'))) {
            $conducteurRepository->remove($conducteur, true);
        }

        return $this->redirectToRoute('app_admin_conducteur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_conducteur/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_conducteur_delete', {'id': conducteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conducteur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_conducteur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_conducteur/edit.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Edit Conducteur{% endblock %}

{% block body %}
    <h1>Edit Conducteur</h1>

    {{ include('admin_conducteur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_conducteur_index') }}">back to list</a>

    {{ include('admin_conducteur/_delete_form.html.twig') }}
{% endblock %}

templates/admin_conducteur/index.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Conducteur index{% endblock %}

{% block body %}
    <h1>Conducteur index</h1>
    <div class="row justify-content-center">

        <div class="col-xl-10">

            <div class="row">


                <div id="responsiveTables" class="mb-5">

                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Nom</th>
                                            <th>Prenom</th>
                                            <th>Email</th>
                                            <th>Ville</th>
                                            <th>Code_postal</th>
                                            <th>Age</th>
                                            <th>Tel</th>
                                            <th>Numero_vol</th>
                                            <th>Adresse</th>
                                            <th>Message</th>
                                            <th>actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for conducteur in conducteurs %}
                                            <tr>
                                                <td>{{ conducteur.id }}</td>
                                                <td>{{ conducteur.nom }}</td>
                                                <td>{{ conducteur.prenom }}</td>
                                                <td>{{ conducteur.email }}</td>
                                                <td>{{ conducteur.ville }}</td>
                                                <td>{{ conducteur.codePostal }}</td>
                                                <td>{{ conducteur.age }}</td>
                                                <td>{{ conducteur.tel }}</td>
                                                <td>{{ conducteur.numeroVol }}</td>
                                                <td>{{ conducteur.adresse }}</td>
                                                <td>{{ conducteur.message }}</td>
                                                <td>
                                                    <a href="{{ path('app_admin_conducteur_show', {'id': conducteur.id}) }}">show</a>
                                                    <a href="{{ path('app_admin_conducteur_edit', {'id': conducteur.id}) }}">edit</a>
                                                </td>
                                            </tr>
                                        {% else %}
                                            <tr>
                                                <td colspan="12">no records found</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="{{ path('app_admin_conducteur_new') }}">Create new</a>
{% endblock %}

templates/admin_conducteur/new.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}New Conducteur{% endblock %}

{% block body %}
    <h1>Create new Conducteur</h1>

    {{ include('admin_conducteur/_form.html.twig') }}

    <a href="{{ path('app_admin_conducteur_index') }}">back to list</a>
{% endblock %}

templates/admin_conducteur/show.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Conducteur{% endblock %}

{% block body %}
    <h1>Conducteur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ conducteur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ conducteur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ conducteur.prenom }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ conducteur.email }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ conducteur.ville }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ conducteur.codePostal }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ conducteur.age }}</td>
            </tr>
            <tr>
                <th>Tel</th>
                <td>{{ conducteur.tel }}</td>
            </tr>
            <tr>
                <th>Numero_vol</th>
                <td>{{ conducteur.numeroVol }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ conducteur.adresse }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ conducteur.message }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_conducteur_index') }}">back to list</a>

    <a href="{{ path('app_admin_conducteur_edit', {'id': conducteur.id}) }}">edit</a>

    {{ include('admin_conducteur/_delete_form.html.twig') }}
{% endblock %}