src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu_prise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lieu_reprise;

    /**
     * @ORM\Column(type="date")
     */
    private $date_prise;

    /**
     * @ORM\Column(type="date")
     */
    private $date_reprise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $heure_prise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $heure_reprise;

    /**
     * @ORM\ManyToOne(targetEntity=Voiture::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_voiture;

    /**
     * @ORM\Column(type="string", length=50, nullable=true, unique=true)
     */
    private $code;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prixTotal;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLieuPrise(): ?string
    {
        return $this->lieu_prise;
    }

    public function setLieuPrise(string $lieu_prise): self
    {
        $this->lieu_prise = $lieu_prise;

        return $this;
    }

    public function getLieuReprise(): ?string
    {
        return $this->lieu_reprise;
    }

    public function setLieuReprise(string $lieu_reprise): self
    {
        $this->lieu_reprise = $lieu_reprise;

        return $this;
    }

    public function getDatePrise(): ?\DateTimeInterface
    {
        return $this->date_prise;
    }

    public function setDatePrise(\DateTimeInterface $date_prise): self
    {
        $this->date_prise = $date_prise;

        return $this;
    }

    public function getDateReprise(): ?\DateTimeInterface
    {
        return $this->date_reprise;
    }

    public function setDateReprise(\DateTimeInterface $date_reprise): self
    {
        $this->date_reprise = $date_reprise;

        return $this;
    }

    public function getHeurePrise(): ?string
    {
        return $this->heure_prise;
    }

    public function setHeurePrise(string $heure_prise): self
    {
        $this->heure_prise = $heure_prise;

        return $this;
    }

    public function getHeureReprise(): ?string
    {
        return $this->heure_reprise;
    }

    public function setHeureReprise(string $heure_reprise): self
    {
        $this->heure_reprise = $heure_reprise;

        return $this;
    }

    public function getIdVoiture(): ?Voiture
    {
        return $this->id_voiture;
    }

    public function setIdVoiture(?Voiture $id_voiture): self
    {
        $this->id_voiture = $id_voiture;

        return $this;
    }

    public function __toString(): string {
        return $this->getId();
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(?string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getPrixTotal(): ?float
    {
        return $this->prixTotal;
    }

    public function setPrixTotal(float $prixTotal): self
    {
        $this->prixTotal = $prixTotal;

        return $this;
    }
}

src/Controller/AdminReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\ReservationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/reservation")
 */
class AdminReservationController extends AbstractController
{
    /**
     * @Route("/", name="app_reservation_index", methods={"GET"})
     */
    public function index(ReservationRepository $reservationRepository): Response
    {
//        dd($reservationRepository->getReservations());
        return $this->render('admin_reservation/index.html.twig', [
            'reservations' => $reservationRepository->getReservations(),
        ]);
    }

    /**
     * @Route("/new", name="app_reservation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, ReservationRepository $reservationRepository): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->add($reservation, true);

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('admin_reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_reservation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->add($reservation, true);

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_reservation_delete", methods={"POST"})
     */
    public function delete(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $reservationRepository->remove($reservation, true);
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_reservation/edit.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>

    {{ include('admin_reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    {{ include('admin_reservation/_delete_form.html.twig') }}
{% endblock %}

templates/admin_reservation/index.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
    <h1>Reservation index</h1>

    <div class="row justify-content-center">

        <div class="col-xl-10">

            <div class="row">


                <div id="responsiveTables" class="mb-5">

                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Lieu_prise</th>
                                        <th>Lieu_reprise</th>
                                        <th>Date_prise</th>
                                        <th>Date_reprise</th>
                                        <th>Heure_prise</th>
                                        <th>Heure_reprise</th>
                                        <th>prix Total</th>
                                        <th>voiture</th>
                                        <th>actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for reservation in reservations %}
                                        <tr>
                                            <td>{{ reservation.id }}</td>
                                            <td>{{ reservation.lieuPrise }}</td>
                                            <td>{{ reservation.lieuReprise }}</td>
                                            <td>{{ reservation.datePrise ? reservation.datePrise|date('Y-m-d') : '' }}</td>
                                            <td>{{ reservation.dateReprise ? reservation.dateReprise|date('Y-m-d') : '' }}</td>
                                            <td>{{ reservation.heurePrise }}</td>
                                            <td>{{ reservation.heureReprise }}</td>
                                            <td>{{ reservation.prixTotal }}</td>
                                            <td>
                                                <a href="{{ path('app_admin_voiture_show', {'id': reservation.idVoiture.id}) }}">
                                                    {{ reservation.idVoiture.marque }}
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{{ path('app_reservation_show', {'id': reservation.id}) }}">show</a>
                                                <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="8">no records found</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <a href="{{ path('app_reservation_new') }}">Create new</a>
{% endblock %}

templates/admin_reservation/new.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('admin_reservation/_form.html.twig') }}

    <a href="{{ path('app_reservation_index') }}">back to list</a>
{% endblock %}

templates/admin_reservation/show.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Lieu_prise</th>
                <td>{{ reservation.lieuPrise }}</td>
            </tr>
            <tr>
                <th>Lieu_reprise</th>
                <td>{{ reservation.lieuReprise }}</td>
            </tr>
            <tr>
                <th>Date_prise</th>
                <td>{{ reservation.datePrise ? reservation.datePrise|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_reprise</th>
                <td>{{ reservation.dateReprise ? reservation.dateReprise|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Heure_prise</th>
                <td>{{ reservation.heurePrise }}</td>
            </tr>
            <tr>
                <th>Heure_reprise</th>
                <td>{{ reservation.heureReprise }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">back to list</a>

    <a href="{{ path('app_reservation_edit', {'id': reservation.id}) }}">edit</a>

    {{ include('admin_reservation/_delete_form.html.twig') }}
{% endblock %}