src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use DateInterval;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VoitureRepository::class)
 */
class Voiture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $carburant;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $transmission;

    /**
     * @ORM\Column(type="integer")
     */
    private $puissance;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $categorie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $agence;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="float")
     */
    private $prix_jour;

    /**
     * @ORM\ManyToOne(targetEntity=Marque::class, inversedBy="voitures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $marque;

    /**
     * @ORM\OneToMany(targetEntity=ImagesVoitures::class, mappedBy="voiture")
     */
    private $imagesVoitures;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\OneToOne(targetEntity=Prix::class, mappedBy="voiture", cascade={"persist", "remove"})
     */
    private $prix;

    private $prixActuel=0;

    public function __construct()
    {
        $this->imagesVoitures = new ArrayCollection();
//        $this->setPrixActuel();
    }

    public function getId(): ?int
    {
        return $this->id;
    }



    public function getCarburant(): ?string
    {
        return $this->carburant;
    }

    public function setCarburant(string $carburant): self
    {
        $this->carburant = $carburant;

        return $this;
    }

    public function getTransmission(): ?string
    {
        return $this->transmission;
    }

    public function setTransmission(string $transmission): self
    {
        $this->transmission = $transmission;

        return $this;
    }

    public function getPuissance(): ?int
    {
        return $this->puissance;
    }

    public function setPuissance(int $puissance): self
    {
        $this->puissance = $puissance;

        return $this;
    }

    public function getAnnee(): ?int
    {
        return $this->annee;
    }

    public function setAnnee(int $annee): self
    {
        $this->annee = $annee;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getAgence(): ?string
    {
        return $this->agence;
    }

    public function setAgence(string $agence): self
    {
        $this->agence = $agence;

        return $this;
    }
    public function __toString():string
    {
        // TODO: Implement __toString() method.
        return 'voiture '.$this->getId().' marque '.$this->getMarque();
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getPrixJour(): ?float
    {
        return $this->prix_jour;
    }

    public function setPrixJour(float $prix_jour): self
    {
        $this->prix_jour = $prix_jour;

        return $this;
    }

    public function getMarque(): ?Marque
    {
        return $this->marque;
    }

    public function setMarque(?Marque $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    /**
     * @return Collection<int, ImagesVoitures>
     */
    public function getImagesVoitures(): Collection
    {
        return $this->imagesVoitures;
    }

    public function addImagesVoiture(ImagesVoitures $imagesVoiture): self
    {
        if (!$this->imagesVoitures->contains($imagesVoiture)) {
            $this->imagesVoitures[] = $imagesVoiture;
            $imagesVoiture->setVoiture($this);
        }

        return $this;
    }

    public function removeImagesVoiture(ImagesVoitures $imagesVoiture): self
    {
        if ($this->imagesVoitures->removeElement($imagesVoiture)) {
            // set the owning side to null (unless already changed)
            if ($imagesVoiture->getVoiture() === $this) {
                $imagesVoiture->setVoiture(null);
            }
        }

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getPrix(): ?Prix
    {
        return $this->prix;
    }

    public function setPrix(?Prix $prix): self
    {
        // unset the owning side of the relation if necessary
        if ($prix === null && $this->prix !== null) {
            $this->prix->setVoiture(null);
        }

        // set the owning side of the relation if necessary
        if ($prix !== null && $prix->getVoiture() !== $this) {
            $prix->setVoiture($this);
        }

        $this->prix = $prix;

        return $this;
    }

    public function getPrixActuel(): ?float
    {
        return $this->prixActuel;
    }

    public function setPrixActuel(): self
    {
        $currentDate = new \DateTime();
        $currentYear = $currentDate->format("Y");
        $dS1 = $currentYear."-".$this->getPrix()->getDateDebutS1();
        $dS2 = $currentYear."-".$this->getPrix()->getDateDebutS2();
        $dS3 = $currentYear."-".$this->getPrix()->getDateDebutS3();
        $dS4 = $currentYear."-".$this->getPrix()->getDateDebutS4();
        $dateDS1 = \DateTime::createFromFormat('Y-m-d', $dS1);
        $dateDS2 = \DateTime::createFromFormat('Y-m-d', $dS2);
        $dateDS3 = \DateTime::createFromFormat('Y-m-d', $dS3);
        $dateDS4 = \DateTime::createFromFormat('Y-m-d', $dS4);
//            Todo: dates finales
        $dateFS1 = \DateTime::createFromFormat('Y-m-d', $dS2);
        $dateFS1->sub(new DateInterval('P1D'));
        $dateFS2 = \DateTime::createFromFormat('Y-m-d', $dS3);
        $dateFS2->sub(new DateInterval('P1D'));
        $dateFS3 = \DateTime::createFromFormat('Y-m-d', $dS4);
        $dateFS3->sub(new DateInterval('P1D'));
        $dateFS4 = \DateTime::createFromFormat('Y-m-d', $dS1);
        $dateFS4
//                ->add(new DateInterval('P1Y'))
            ->sub(new DateInterval('P1D'));
        $prixActuel = $this->getPrixJour();
        if ($currentDate >= $dateDS1 && $currentDate <= $dateFS1){
            $prixActuel = $this->getPrix()->getPrixS1();
//            dd('true s1: ',$dS1, $this->getPrix()->getPrixS1(),$dateFS1);
        }
        else if ($currentDate >= $dateDS2 && $currentDate <= $dateFS2){
            $prixActuel = $this->getPrix()->getPrixS2();
//            dd('true s2: ',$dS2, $this->getPrix()->getPrixS2(),$dateFS2);
        }
        else if ($currentDate >= $dateDS3 && $currentDate <= $dateFS3){
            $prixActuel = $this->getPrix()->getPrixS3();
//            dd('true s3: ',$dS3, $this->getPrix()->getPrixS3(),$dateFS3);
        }
        else if ($currentDate >= $dateDS4 && $currentDate <= $dateFS4){
            $prixActuel = $this->getPrix()->getPrixS4();
//            dd('true s4: ',$dS4, $this->getPrix()->getPrixS4(),$dateFS4);
        }
        $this->prixActuel = $prixActuel;

        return $this;
    }


}

src/Controller/AdminVoitureController.php
<?php

namespace App\Controller;

use App\Entity\Voiture;
use App\Form\VoitureType;
use App\Repository\VoitureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * @Route("/admin/voiture")
 */
class AdminVoitureController extends AbstractController
{

    private RequestStack $requestStack;

    public function __construct(RequestStack $requestStack){

        $this->requestStack = $requestStack;
    }

    /**
     * @Route("/", name="app_admin_voiture_index", methods={"GET"})
     */
    public function index(VoitureRepository $voitureRepository): Response
    {
        $voitures = $voitureRepository->findAll();
        foreach ($voitures as $voiture) {
            $voiture->setPrixActuel();
        }
        return $this->render('admin_voiture/index.html.twig', [
            'voitures' => $voitures,
        ]);
    }

    /**
     * @Route("/new", name="app_admin_voiture_new", methods={"GET", "POST"})
     */
    public function new(Request $request, VoitureRepository $voitureRepository, SluggerInterface $slugger): Response
    {
        $voiture = new Voiture();
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $form->get('image')->getData();
            if ($file) {
                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('voiture_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $code = $voiture->getMarque().' '.uniqid();
                $voiture->setImage($newFilename);
                $voiture->setCode($code);
                $voitureRepository->add($voiture, true);
                $session = $this->requestStack->getSession();
                $session->set('code_voiture', $code);
                return $this->redirectToRoute('app_admin_prix_new', [], Response::HTTP_SEE_OTHER);
            }
        }

        return $this->renderForm('admin_voiture/new.html.twig', [
            'voiture' => $voiture,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_voiture_show", methods={"GET"})
     */
    public function show(Voiture $voiture): Response
    {
//        dd(uniqid());
        return $this->render('admin_voiture/show.html.twig', [
            'voiture' => $voiture,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_admin_voiture_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Voiture $voiture, VoitureRepository $voitureRepository, SluggerInterface $slugger): Response
    {
        $form = $this->createForm(VoitureType::class, $voiture);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
               $voitureRepository->add($voiture, true);
            $file = $form->get('image')->getData();
            if ($file) {
                $originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . uniqid() . '.' . $file->guessExtension();

                // Move the file to the directory where brochures are stored
                try {
                    $file->move(
                        $this->getParameter('voiture_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $voiture->setImage($newFilename);
                $voitureRepository->add($voiture, true);

                return $this->redirectToRoute('app_admin_voiture_index', [], Response::HTTP_SEE_OTHER);
            }
            return $this->redirectToRoute('app_admin_voiture_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_voiture/edit.html.twig', [
            'voiture' => $voiture,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_admin_voiture_delete", methods={"POST"})
     */
    public function delete(Request $request, Voiture $voiture, VoitureRepository $voitureRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$voiture->getId(), $request->request->get('_token'))) {
            $voitureRepository->remove($voiture, true);
        }

        return $this->redirectToRoute('app_admin_voiture_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_voiture/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_voiture_delete', {'id': voiture.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ voiture.id) }}">
    <button class="btn">Delete</button>
</form>

templates/admin_voiture/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.marque) }}
    {{ form_row(form.carburant) }}
    {{ form_row(form.transmission) }}
    {{ form_row(form.puissance) }}
    {{ form_row(form.categorie) }}
    {{ form_row(form.annee) }}
    {{ form_row(form.agence) }}
    {{ form_row(form.image) }}
    {{ form_row(form.prixJour) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_voiture/edit.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Edit Voiture{% endblock %}

{% block body %}
    <h1>Edit Voiture</h1>

    {{ include('admin_voiture/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_voiture_index') }}">back to list</a>

    {{ include('admin_voiture/_delete_form.html.twig') }}
{% endblock %}

templates/admin_voiture/index.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Voiture index{% endblock %}

{% block body %}
    <h1>Voiture index</h1>

    <div class="row justify-content-center">

        <div class="col-xl-10">

            <div class="row">


                <div id="responsiveTables" class="mb-5">

                    <div class="card">
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table mb-0">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Marque</th>
                                        <th>Carburant</th>
                                        <th>Transmission</th>
                                        <th>Puissance</th>
                                        <th>Annee</th>
                                        <th>Categorie</th>
                                        <th>Agence</th>
                                        <th>image</th>
                                        <th>code</th>
                                        <th>prix jour</th>
                                        <th>prix Actuel</th>
                                        <th>actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for voiture in voitures %}
                                        <tr>
                                            <td>{{ voiture.id }}</td>
                                            <td>{{ voiture.marque }}</td>
                                            <td>{{ voiture.carburant }}</td>
                                            <td>{{ voiture.transmission }}</td>
                                            <td>{{ voiture.puissance }}</td>
                                            <td>{{ voiture.annee }}</td>
                                            <td>{{ voiture.categorie }}</td>
                                            <td>{{ voiture.agence }}</td>
                                            <td>
                                                <img src="{{ asset('admin/img/voiture/'~voiture.image) }}"
                                                     class="img-fluid d-block m-auto" alt="{{ voiture.marque }}"
                                                     width="50px">
                                            </td>
                                            <td>
                                                {{ voiture.code }}
                                            </td>
                                            <td>
                                                {{ voiture.prixJour }}
                                            </td>
                                            <td>
                                                {{ voiture.prixActuel }}
                                            </td>
                                            <td>
                                                <a href="{{ path('app_admin_voiture_show', {'id': voiture.id}) }}">show</a>
                                                <a href="{{ path('app_admin_voiture_edit', {'id': voiture.id}) }}">edit</a>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="9">no records found</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>



                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="{{ path('app_admin_voiture_new') }}">Create new</a>
    </div>
{% endblock %}

templates/admin_voiture/new.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}New Voiture{% endblock %}

{% block body %}
    <h1>Create new Voiture</h1>

    {{ include('admin_voiture/_form.html.twig') }}

    <a href="{{ path('app_admin_voiture_index') }}">back to list</a>
{% endblock %}

templates/admin_voiture/show.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Voiture{% endblock %}

{% block body %}
    <h1>Voiture</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ voiture.id }}</td>
            </tr>
            <tr>
                <th>Marque</th>
                <td>{{ voiture.marque }}</td>
            </tr>
            <tr>
                <th>Carburant</th>
                <td>{{ voiture.carburant }}</td>
            </tr>
            <tr>
                <th>Transmission</th>
                <td>{{ voiture.transmission }}</td>
            </tr>
            <tr>
                <th>Puissance</th>
                <td>{{ voiture.puissance }}</td>
            </tr>
            <tr>
                <th>Annee</th>
                <td>{{ voiture.annee }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ voiture.categorie }}</td>
            </tr>
            <tr>
                <th>Agence</th>
                <td>{{ voiture.agence }}</td>
            </tr>
            <tr>
                <th>Code</th>
                <td>{{ voiture.code }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_voiture_index') }}">back to list</a>

    <a href="{{ path('app_admin_voiture_edit', {'id': voiture.id}) }}">edit</a>

    {{ include('admin_voiture/_delete_form.html.twig') }}
{% endblock %}